services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: desafiotech_bd
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  sua-api:
    build: .
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
volumes:
  postgres_data:
  minio_data: